@Library("jenlib") _

wafDefaultPipeline(projects: ["fisch"],
                   container: [app: "visionary-dls"],
                   testSlurmResource: [partition: "cube", wafer: 62, "fpga-without-aout": 3],
                   testOptions: "-j1 --test-execall",
                   testTimeout: 240,
                   notificationChannel: "#dls-software")
