@Library("jenlib@ebrains-2.0") _

Map<String, Object> pipelineOptions = [
		projects: ["fisch"],
		setupOptions: "--release-branch=ebrains-2.0",
		moduleOptions: [modules: ["ppu-toolchain"]],
		container: [app: "dls-core"],
		notificationChannel: "#dls-software",
		configureInstallOptions: "--build-profile=ci"
]

if (!isTriggeredByGerrit()) {
	pipelineOptions << [
			testSlurmResource: [partition: "cube", wafer: 62, "fpga-without-aout": 0],
			preTestHook: { configureHxCubeBitfile() },
			testOptions: "--test-execall -j1",
	]
}

withCcache() {
	wafDefaultPipeline(pipelineOptions)
}
