#pragma once
#include "halco/hicann-dls/vx/barrier.h"
#include "halco/hicann-dls/vx/fpga.h"
#include "halco/hicann-dls/vx/i2c.h"
#include "halco/hicann-dls/vx/jtag.h"
#include "halco/hicann-dls/vx/omnibus.h"
#include "halco/hicann-dls/vx/reset.h"
#include "halco/hicann-dls/vx/spi.h"
#include "halco/hicann-dls/vx/timing.h"
