#!/usr/bin/env python
from waflib.extras.test_base import summary

def depends(ctx):
    ctx('fisch')
    ctx('halco', 'pyhalco')


def options(opt):
    pass


def configure(cfg):
    cfg.load('compiler_cxx')
    cfg.load('python')
    cfg.check_python_version()
    cfg.check_python_headers()
    cfg.load('pytest')
    cfg.load('genpybind')

    cfg.check(
        compiler='cxx',
        features='cxx pyembed',
        uselib_store='PYBIND11FISCH',
        mandatory=True,
        header_name='pybind11/pybind11.h',
    )


def build(bld):
    bld(
        target='pyfisch_vx',
        source='../include/fisch/vx/fisch.h',
        genpybind_tags='fisch_vx',
        features='genpybind cxx cxxshlib pyext',
        use=['fisch_vx', 'PYBIND11FISCH', 'pyhalco_hicann_dls_vx'],
        install_path='${PREFIX}/lib',
        linkflags='-Wl,-z,defs',
    )

    bld(
        target='pyfisch_swtests_vx',
        tests=bld.path.ant_glob('tests/sw/*.py'),
        features='use pytest',
        use='pyfisch_vx',
        install_path='${PREFIX}/bin',
        pythonpath=['tests'],
    )

    bld(
        target='pyfisch_hwtests_vx',
        tests=bld.path.ant_glob('tests/hw/*.py'),
        features='use pytest',
        use='pyfisch_vx',
        install_path='${PREFIX}/bin',
        skip_run=True,
        pythonpath=['tests'],
    )

    bld.add_post_fun(summary)
