#!/usr/bin/env python
from waflib.extras.test_base import summary

def depends(ctx):
    ctx('fisch')
    ctx('halco', 'pyhalco')


def options(opt):
    pass


def configure(cfg):
    cfg.load('compiler_cxx')
    cfg.load('python')
    cfg.check_python_version()
    cfg.check_python_headers()
    cfg.load('pytest')
    cfg.load('genpybind')


def build(bld):
    for hx_version in [2, 3]:
        bld(
            target=f'pyfisch_vx_v{hx_version}',
            source='../include/fisch/vx/python_bindings.h',
            genpybind_tags='fisch_vx',
            features='genpybind cxx cxxshlib pyext',
            use=[f'fisch_vx_v{hx_version}',
                 f'pyhalco_hicann_dls_vx_v{hx_version}',
                 'pyhxcomm_vx'],
            install_path='${PREFIX}/lib',
            defines = [f'FISCH_VX_CHIP_VERSION={hx_version}'],
        )

        bld(
            target=f'pyfisch_swtest_vx_v{hx_version}',
            tests=bld.path.ant_glob(f'tests/sw/fisch-v{hx_version}-*.py'),
            features='use pytest',
            use=f'pyfisch_vx_v{hx_version}',
            install_path='${PREFIX}/bin',
            pythonpath=['tests'],
        )

    bld.add_post_fun(summary)
